package com.blueocean.web.pharmacymanage.dao;

import org.apache.ibatis.annotations.Mapper;

import com.blueocean.web.pharmacymanage.dto.DrugInfoDo;

@Mapper
public interface DruginfoDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    int deleteByPrimaryKey(String goodsUpc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    int insert(DrugInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    int insertSelective(DrugInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    DrugInfoDo selectByPrimaryKey(String goodsUpc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    int updateByPrimaryKeySelective(DrugInfoDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    int updateByPrimaryKey(DrugInfoDo record);
}