package com.blueocean.web.pharmacymanage.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

import com.blueocean.web.pharmacymanage.dto.DrugListDo;
import com.blueocean.web.pharmacymanage.dto.DrugOrderDetailDo;
import com.blueocean.web.pharmacymanage.dto.DrugOrderDo;
import com.blueocean.web.pharmacymanage.dto.DrugOrderListDo;

@Mapper
public interface DrugOrderDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int insert(DrugOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int insertSelective(DrugOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    DrugOrderDo selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int updateByPrimaryKeySelective(DrugOrderDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drug_order
     *
     * @mbggenerated Tue Jul 25 15:09:42 CST 2017
     */
    int updateByPrimaryKey(DrugOrderDo record);
    
    /**
     * 
     * @param params
     * @return
     */
	List<DrugOrderListDo> listDrugOrderByParams(Map<String, Object> params);
	
	/**
	 * 
	 * @param orderId
	 * @return
	 */
	DrugOrderDetailDo selectDrugOrderDetail(String orderId);
	/**
	 * 
	 * @param orderId
	 * @return
	 */
	List<DrugListDo> selectDrugInfoByOrderId(String orderId);
}