package com.blueocean.web.pharmacymanage.dto;

import java.io.Serializable;

public class DrugInfoDo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.goods_upc
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String goodsUpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.goods_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.brand_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.primary_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String primaryCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.second_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String secondCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.third_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String thirdCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.weight
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.generaL_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String generalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.drug_standard
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String drugStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.prescription_type
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String prescriptionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.take_type
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String takeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.placeoforigin
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String placeoforigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.intended_for
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String intendedFor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.functions
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String functions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.approval_number
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String approvalNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.properties
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String properties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.dosage
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String dosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.adverse_reaction
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String adverseReaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.avoid
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String avoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.attention
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String attention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.interaction
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String interaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.validity
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private Integer validity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.produce_enterprise
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String produceEnterprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.component
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.storage_way
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String storageWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.drug_package
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String drugPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.implementation_standards
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String implementationStandards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.dosage_form
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String dosageForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.pharmacokinetics
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String pharmacokinetics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.keyword
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.pharmacological_action
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String pharmacologicalAction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column druginfo.drug_pic
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private String drugPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table druginfo
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.goods_upc
     *
     * @return the value of druginfo.goods_upc
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getGoodsUpc() {
        return goodsUpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.goods_upc
     *
     * @param goodsUpc the value for druginfo.goods_upc
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setGoodsUpc(String goodsUpc) {
        this.goodsUpc = goodsUpc == null ? null : goodsUpc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.goods_name
     *
     * @return the value of druginfo.goods_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.goods_name
     *
     * @param goodsName the value for druginfo.goods_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.brand_name
     *
     * @return the value of druginfo.brand_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.brand_name
     *
     * @param brandName the value for druginfo.brand_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.primary_category
     *
     * @return the value of druginfo.primary_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getPrimaryCategory() {
        return primaryCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.primary_category
     *
     * @param primaryCategory the value for druginfo.primary_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setPrimaryCategory(String primaryCategory) {
        this.primaryCategory = primaryCategory == null ? null : primaryCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.second_category
     *
     * @return the value of druginfo.second_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getSecondCategory() {
        return secondCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.second_category
     *
     * @param secondCategory the value for druginfo.second_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setSecondCategory(String secondCategory) {
        this.secondCategory = secondCategory == null ? null : secondCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.third_category
     *
     * @return the value of druginfo.third_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getThirdCategory() {
        return thirdCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.third_category
     *
     * @param thirdCategory the value for druginfo.third_category
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setThirdCategory(String thirdCategory) {
        this.thirdCategory = thirdCategory == null ? null : thirdCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.weight
     *
     * @return the value of druginfo.weight
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.weight
     *
     * @param weight the value for druginfo.weight
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.generaL_name
     *
     * @return the value of druginfo.generaL_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getGeneralName() {
        return generalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.generaL_name
     *
     * @param generalName the value for druginfo.generaL_name
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setGeneralName(String generalName) {
        this.generalName = generalName == null ? null : generalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.drug_standard
     *
     * @return the value of druginfo.drug_standard
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getDrugStandard() {
        return drugStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.drug_standard
     *
     * @param drugStandard the value for druginfo.drug_standard
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setDrugStandard(String drugStandard) {
        this.drugStandard = drugStandard == null ? null : drugStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.prescription_type
     *
     * @return the value of druginfo.prescription_type
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getPrescriptionType() {
        return prescriptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.prescription_type
     *
     * @param prescriptionType the value for druginfo.prescription_type
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setPrescriptionType(String prescriptionType) {
        this.prescriptionType = prescriptionType == null ? null : prescriptionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.take_type
     *
     * @return the value of druginfo.take_type
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getTakeType() {
        return takeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.take_type
     *
     * @param takeType the value for druginfo.take_type
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setTakeType(String takeType) {
        this.takeType = takeType == null ? null : takeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.placeoforigin
     *
     * @return the value of druginfo.placeoforigin
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getPlaceoforigin() {
        return placeoforigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.placeoforigin
     *
     * @param placeoforigin the value for druginfo.placeoforigin
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setPlaceoforigin(String placeoforigin) {
        this.placeoforigin = placeoforigin == null ? null : placeoforigin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.intended_for
     *
     * @return the value of druginfo.intended_for
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getIntendedFor() {
        return intendedFor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.intended_for
     *
     * @param intendedFor the value for druginfo.intended_for
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setIntendedFor(String intendedFor) {
        this.intendedFor = intendedFor == null ? null : intendedFor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.functions
     *
     * @return the value of druginfo.functions
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getFunctions() {
        return functions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.functions
     *
     * @param functions the value for druginfo.functions
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setFunctions(String functions) {
        this.functions = functions == null ? null : functions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.approval_number
     *
     * @return the value of druginfo.approval_number
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getApprovalNumber() {
        return approvalNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.approval_number
     *
     * @param approvalNumber the value for druginfo.approval_number
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setApprovalNumber(String approvalNumber) {
        this.approvalNumber = approvalNumber == null ? null : approvalNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.properties
     *
     * @return the value of druginfo.properties
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getProperties() {
        return properties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.properties
     *
     * @param properties the value for druginfo.properties
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setProperties(String properties) {
        this.properties = properties == null ? null : properties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.dosage
     *
     * @return the value of druginfo.dosage
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getDosage() {
        return dosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.dosage
     *
     * @param dosage the value for druginfo.dosage
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setDosage(String dosage) {
        this.dosage = dosage == null ? null : dosage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.adverse_reaction
     *
     * @return the value of druginfo.adverse_reaction
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getAdverseReaction() {
        return adverseReaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.adverse_reaction
     *
     * @param adverseReaction the value for druginfo.adverse_reaction
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setAdverseReaction(String adverseReaction) {
        this.adverseReaction = adverseReaction == null ? null : adverseReaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.avoid
     *
     * @return the value of druginfo.avoid
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getAvoid() {
        return avoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.avoid
     *
     * @param avoid the value for druginfo.avoid
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setAvoid(String avoid) {
        this.avoid = avoid == null ? null : avoid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.attention
     *
     * @return the value of druginfo.attention
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getAttention() {
        return attention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.attention
     *
     * @param attention the value for druginfo.attention
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setAttention(String attention) {
        this.attention = attention == null ? null : attention.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.interaction
     *
     * @return the value of druginfo.interaction
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getInteraction() {
        return interaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.interaction
     *
     * @param interaction the value for druginfo.interaction
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setInteraction(String interaction) {
        this.interaction = interaction == null ? null : interaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.validity
     *
     * @return the value of druginfo.validity
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public Integer getValidity() {
        return validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.validity
     *
     * @param validity the value for druginfo.validity
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setValidity(Integer validity) {
        this.validity = validity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.produce_enterprise
     *
     * @return the value of druginfo.produce_enterprise
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getProduceEnterprise() {
        return produceEnterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.produce_enterprise
     *
     * @param produceEnterprise the value for druginfo.produce_enterprise
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setProduceEnterprise(String produceEnterprise) {
        this.produceEnterprise = produceEnterprise == null ? null : produceEnterprise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.component
     *
     * @return the value of druginfo.component
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.component
     *
     * @param component the value for druginfo.component
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.storage_way
     *
     * @return the value of druginfo.storage_way
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getStorageWay() {
        return storageWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.storage_way
     *
     * @param storageWay the value for druginfo.storage_way
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setStorageWay(String storageWay) {
        this.storageWay = storageWay == null ? null : storageWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.drug_package
     *
     * @return the value of druginfo.drug_package
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getDrugPackage() {
        return drugPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.drug_package
     *
     * @param drugPackage the value for druginfo.drug_package
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setDrugPackage(String drugPackage) {
        this.drugPackage = drugPackage == null ? null : drugPackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.implementation_standards
     *
     * @return the value of druginfo.implementation_standards
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getImplementationStandards() {
        return implementationStandards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.implementation_standards
     *
     * @param implementationStandards the value for druginfo.implementation_standards
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setImplementationStandards(String implementationStandards) {
        this.implementationStandards = implementationStandards == null ? null : implementationStandards.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.dosage_form
     *
     * @return the value of druginfo.dosage_form
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getDosageForm() {
        return dosageForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.dosage_form
     *
     * @param dosageForm the value for druginfo.dosage_form
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setDosageForm(String dosageForm) {
        this.dosageForm = dosageForm == null ? null : dosageForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.pharmacokinetics
     *
     * @return the value of druginfo.pharmacokinetics
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getPharmacokinetics() {
        return pharmacokinetics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.pharmacokinetics
     *
     * @param pharmacokinetics the value for druginfo.pharmacokinetics
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setPharmacokinetics(String pharmacokinetics) {
        this.pharmacokinetics = pharmacokinetics == null ? null : pharmacokinetics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.keyword
     *
     * @return the value of druginfo.keyword
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.keyword
     *
     * @param keyword the value for druginfo.keyword
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.pharmacological_action
     *
     * @return the value of druginfo.pharmacological_action
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getPharmacologicalAction() {
        return pharmacologicalAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.pharmacological_action
     *
     * @param pharmacologicalAction the value for druginfo.pharmacological_action
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setPharmacologicalAction(String pharmacologicalAction) {
        this.pharmacologicalAction = pharmacologicalAction == null ? null : pharmacologicalAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column druginfo.drug_pic
     *
     * @return the value of druginfo.drug_pic
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public String getDrugPic() {
        return drugPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column druginfo.drug_pic
     *
     * @param drugPic the value for druginfo.drug_pic
     *
     * @mbggenerated Thu Jul 27 10:17:40 CST 2017
     */
    public void setDrugPic(String drugPic) {
        this.drugPic = drugPic == null ? null : drugPic.trim();
    }
}